config/routes.rb
Joinplato::Application.routes.draw do

  # redirect www to .
  match "/" => redirect("http://voxe.org"), :constraints => {:subdomain => "www"}
  match "/*path" => redirect {|params, request| "http://voxe.org/#{params[:path]}" }, :constraints => {:subdomain => "www"}

  # 2008
  match "/election-municipales" => redirect('/')
  match "/election-municipales/" => redirect('/')
  match "/election-municipales/*path" => redirect('/')

  # sitemap
  match 'sitemap.xml' => 'web/sitemap#index', format: 'xml'

  # admin
  namespace :admin do
    match '/' => 'dashboard#index'
  end

  # New admin (Let the old live until candidate BO isn't finished)
  namespace :new_admin do
    match '/' => 'elections#index'
    resources :countries
    resources :tags
    resources :elections do
      resources :election_tags, only: [:index]
      resources :candidacies do
          get 'toggle', :defaults => { :format => 'json' }
        resources :propositions
        match 'propositions/categorie/:namespace_categ' => 'propositions#index', :as => :propositions_categorie
      end
      get 'publish', :defaults => { :format => 'json' }
      get 'unpublish', :defaults => { :format => 'json' }
      resources :tags, only: [:create]
      resources :ambassadors
      resources :contributors
    end
    resources :candidacy_candidate_profiles
    resources :candidates
    resources :tags, only: [:index, :edit, :update]
    resources :users, only: [:index]
    resources :manage_propositions, only: [:index]
  end

  # API
  namespace :api, format: :json do
    namespace :v1 do

      resources :elections, except: :index do
        member do
          post :addtag
          delete :removetag
          post :addcandidacy
          post :movetags
          post :addcontributor
          get :contributors
          post :addambassador
          get :ambassadors
          post :addcontributor
          get :contributors
        end
        collection do
          get :search
        end
      end

      resources :themes do
        member do
          post :addphoto
        end
      end

      resources :candidates do
        member do
          post :addphoto
        end
        collection do
          get :search
        end
      end

      resources :tags do
        collection do
          get :search
        end
      end

      resources :propositions do
        scope module: :user_actions do
          resource :favorite, only: [:create, :destroy]
          resource :support, only: [:create, :destroy]
          resource :against, only: [:create, :destroy]
        end
        collection do
          get :search
        end
        member do
          get :comments
          post :addcomment
          post :addembed
          delete :removeembed
          delete :removecomment
        end
      end

      resources :candidacies do
        member do
          post :addorganization
        end
      end

      resources :users do
        collection do
          get :search
          get :verify
          get :self
          put :self
          get :facebookconnect
          get :admins
        end
        member do
          put :addadmin
          put :removeadmin
        end
      end

      resources :organizations

      resources :comparisons do
        collection do
          get :search
        end
      end

      resources :countries do
        collection do
          get :search
        end
      end

      resources :cities do
        get :search, on: :collection
      end

    end
  end

  # webviews
  namespace :webviews, format: "touch" do
    resources :comparisons, only: :index
    resources :propositions, only: :show
  end

  # web-app
  namespace :embed do
    resources :elections, only: :show
    resources :live, only: :index
    resources :partners, only: :index do
      collection do
        get :huffingtonpost
      end
    end
  end

  # api doc

  match 'platform' => 'platform#index'

  namespace :platform do
    resources :endpoints do
      collection do
        get :elections
        get :candidates
        get :propositions
        get :tags
        get :candidacies
        get :users
        get :organizations
        get :countries
      end
    end
    resources :models do
      collection do
        get :election
        get :candidate
        get :proposition
        get :tag
        get :candidacy
        get :user
        get :organization
        get :country
      end
    end
    resources :embed, :only => :index do
      collection do
        get :button
        get :bookmarklet
      end
    end
    resources :mobile, :only => :index
    resources :open_data, :only => :index
  end

  devise_for :users, controllers: {
    sessions: "devise/custom_sessions"
  }

  # Back-office for candidates
  namespace :backoffice do
    root to: 'my_profiles#show'
    resources :candidacies
    resource :my_profile do
      member do
        get :thank_you
      end
    end
    resources :propositions
    match 'propositions/categorie/:namespace_categ' => 'propositions#index', :as => :propositions_categorie
  end

  # all platforms
  match 'about/' => 'Web::Static#about', :as => :about
  match 'about/how' => 'Web::Static#how', :as => :how
  match 'about/team' => 'Web::Static#team', :as => :team
  match 'about/press' => 'Web::Static#press', :as => :press
  match 'about/thanks' => 'Web::Static#thanks', :as => :thanks
  match 'apps' => 'Web::Static#apps', :as => :apps

  # touch
  scope :module => "touch", format: "touch", constraints: TouchConstraint.new do
    root to: 'application#welcome'
    get '/welcome' => 'application#welcome', :as => :welcome
    match ':namespace/:candidacies/:tag' => 'comparisons#show', :as => :compare
    match ':namespace/:candidacies' => 'tags#index', :as => :tags
    match ':namespace' => 'elections#show', :as => :election

    root to: 'elections#index'
  end

  # mobile
  scope :module => "mobile", format: "mobile", constraints: MobileConstraint.new do
    match ':namespace/:candidacies/:tag' => 'elections#compare', :as => :compare

    match 'propositions/:id' => 'propositions#show', :as => :proposition

    match ':namespace/candidacies' => 'candidacies#create', :as => :candidacies
    match ':namespace/:candidacies' => 'tags#index', :as => :tags
    match ':namespace' => 'elections#show', :as => :election

    root to: 'elections#index'
  end

  # web
  scope :module => "web", format: "html" do
    match 'welcome' => 'application#welcome', :as => :welcome

    match 'propositions/:id' => 'propositions#show', :as => :proposition
    match 'country-:countrynamespace' => 'countries#show', :as => :country
    match 'election/:electionnamespace/candidate/:candidatenamespace' => 'candidacy_candidate_profiles#show', as: :candidate_profile
    match 'citizen/:id' => 'citizen_profiles#show', as: :citizen_profiles
    match ':namespace/:candidacies/:tag' => 'comparisons#show', :as => :compare
    match ':namespace/:candidacies' => 'tags#index', :as => :tags
    match ':namespace' => 'elections#show', :as => :election

    root to: 'application#index'
  end

end

app/controllers/api/v1/propositions_controller.rb
class Api::V1::PropositionsController < Api::V1::ApplicationController

  # POST /api/v1/propositions
  def create
    params[:proposition] ||= {}
    tags = Tag.any_in(_id: params[:proposition][:tagIds].split(',')) if params[:proposition][:tagIds]
    @proposition = Proposition.new(
      text:         params[:proposition][:text],
      candidacy_id: params[:proposition][:candidacyId],
      tags:          tags
    )

    if @proposition.save
      render 'api/v1/propositions/show'
    else
      render text: {errors: @proposition.errors}.to_json, status: :unprocessable_entity, layout: 'api_v1'
    end
  end
  
  # GET /api/v1/propositions/search
  # params electionIds, tagIds, candidacyIds
  def search
    # query
    conditions = {}
    unless params[:tagIds].blank?
      conditions[:tag_ids.in] = tag_ids = params[:tagIds].split(',')
    end
    unless params[:candidacyIds].blank?
      conditions[:candidacy_id.in] = candidacy_ids = params[:candidacyIds].split(',')
    end
    
    # pagination
    skip = params[:offset] || 0
    limit = 500
    if params[:limit]
      limit = params[:limit].to_i
    end
    @propositions = Proposition.includes(:candidacy).where(conditions).limit(limit).skip(skip)

    # Logging
    Event.create name: 'comparison', candidacy_ids: candidacy_ids, tag_ids: tag_ids, ip_address: request.remote_ip.inspect, user_driven: params[:userDriven]
  end
  
  # GET /api/v1/propositions
  def show
  end

  # PUT /api/v1/propositions/1
  def update
    params[:proposition] ||= {}
    if params[:proposition][:tagIds]
      @proposition.tags = Tag.any_in(_id: params[:proposition][:tagIds].split(','))
    end
    if params[:proposition][:text]
      @proposition.text = params[:proposition][:text]
    end

    if @proposition.save
      render 'api/v1/propositions/show'
    else
      render text: {errors: @proposition.errors}.to_json, status: :unprocessable_entity, layout: 'api_v1'
    end
  end

  # DELETE /api/v1/propositions/1
  def destroy
    @proposition.destroy
    head :ok
  end

  # POST /api/v1/propositions/1/addcomment
  def addcomment
    @comment = @proposition.comments.build text: params[:text]
    @comment.user = current_user
    
    if @comment.save
      render 'api/v1/comments/show'
    else
      render text: {errors: @comment.errors}.to_json, status: :unprocessable_entity, layout: 'api_v1'
    end
  end

  # GET /api/v1/propositions/1/comments
  def comments
    @comments = @proposition.comments.includes(:user)
  end

  # POST /api/v1/propositions/1/addembed
  def addembed
    transform_youtube_url_shortner_links
    @embed = @proposition.embeds.build url: params[:url], title: params[:title]
    if @embed.save
      render 'api/v1/propositions/show'
    else
      render text: {errors: @embed.errors}.to_json, status: :unprocessable_entity, layout: 'api_v1'
    end
  end

  # DELETE /api/v1/propositions/1/removeembed
  def removeembed
    embed = @proposition.embeds.find params[:embedId]
    if embed.destroy
      head :ok
    else
      render text: {errors: embed.errors}.to_json, status: :unprocessable_entity, layout: 'api_v1'
    end
  end

  # DELETE /api/v1/propositions/1/removecomment
  def removecomment
    comment = @proposition.comments.find params[:commentId]
    authorize! :destroy, comment
    if comment.destroy
      head :ok
    else
      render text: {errors: comment.errors}.to_json, status: :unprocessable_entity, layout: 'api_v1'
    end
  end

  protected
    def transform_youtube_url_shortner_links
      params[:url] = params[:url].gsub /^http:\/\/youtu.be\/(\w+)$/, 'http://www.youtube.com/watch?v=\\1'
    end
end

app/controllers/backoffice/backoffice_controller.rb
class Backoffice::BackofficeController < ApplicationController
  layout 'backoffice'
  respond_to :html, :json
  before_filter :authenticate_user!
  before_filter :set_locale

  protected

  def current_ability
    @_current_ability ||= BackofficeAbility.new(current_user)
  end

  def load_profile
    if user_signed_in?
      @profile ||= current_user.candidacy_candidate_profile
    end
  end

  def load_candidacy
    @candidacy = @profile.candidacy
  end

  def load_election
    @election = @candidacy.election
  end

  def set_locale
    I18n.locale = :fr if Rails.env.development?
  end

end

app/controllers/backoffice/candidacies_controller.rb
class Backoffice::CandidaciesController < ApplicationController
  load_and_authorize_resource class: 'Candidacy'
  before_filter :load_election
  layout 'backoffice'

  def show
  end

  private

  def load_election
    @election = @candidacy.election
  end
end

app/controllers/backoffice/candidates_controller.rb
class Backoffice::CandidatesController < Backoffice::BackofficeController
  def show
    redirect_to action: :edit
  end

  def edit
  end

  def update
    current_candidate.update_attributes params[:candidate]
    respond_with current_candidate, location: backoffice_candidate_path
  end

end

app/controllers/backoffice/my_profiles_controller.rb
class Backoffice::MyProfilesController < Backoffice::BackofficeController
  skip_before_filter :authenticate_user!, only: [:new, :create, :thank_you]
  before_filter :load_profile, only: [:show, :edit, :update]

  def show
    @no_signed = true
    unless @profile.nil?
      redirect_to action: :edit
    end
  end

  def new
    redirect_to action: :show if user_signed_in?
    @profile = CandidacyCandidateProfile.new
  end

  def create
    redirect_to :show if user_signed_in?
    @profile = CandidacyCandidateProfile.new params[:candidacy_candidate_profile]
    existing_profile = CandidacyCandidateProfile.where(email: @profile.email)
    if existing_profile.count == 0

      if @profile.save
        redirect_to thank_you_backoffice_my_profile_path
      else
        redirect_to :back, alert: "Une erreur est survenue lors de votre inscription, veuillez réessayer."
      end
    else
      redirect_to :back, alert: "Cet mail est déjà utilisé"
    end
  end

  def thank_you
  end

  def edit
    @election = @profile.candidacy.election
  end

  def update
    @profile.update_attributes params[:candidacy_candidate_profile]
    flash[:notice] = "Votre profil a été mis à jour"
    respond_with @profile, location: backoffice_my_profile_path
  end

end

app/controllers/backoffice/propositions_controller.rb
# encoding: UTF-8
class Backoffice::PropositionsController < Backoffice::BackofficeController
  before_filter :load_profile
  before_filter :load_candidacy
  before_filter :load_election
  # load_and_authorize_resource :election, :proposition
  before_filter :load_proposition, :only => [:edit, :update, :destroy]
  before_filter :load_proposition_tags, :only => [:edit]

  def index
    @election_name = @candidacy.election.name
    if (params[:namespace_categ])
      @active_tag = @candidacy.election.election_tags.select{ |election_tag| election_tag.tag.namespace == params[:namespace_categ] }.first
      @propositions_categ = @candidacy.propositions.select{ |proposition| proposition.tag_ids.include?(@active_tag.tag_id) }
    else
      @active_tag = nil
      @propositions_categ = []
    end
    @lst_tags = @candidacy.election.election_tags.where(:parent_tag_id => nil)

  end

  def new
    gon.page = "new"
    @proposition = Proposition.new
    load_select_tag
  end

  def create
    params[:proposition][:tag_ids].delete("")
    @proposition = @candidacy.propositions.build(params[:proposition])
    election_tag = @candidacy.election.election_tags.find(params[:election_tag_id])
    @tags = election_tag.children_election_tags.map &:tag
    if @proposition.save
      redirect_to backoffice_propositions_path(namespace_categ: election_tag.tag.namespace), notice: 'Votre proposition a été ajoutée'
    else
      redirect_to :back, alert: 'Une erreur est survenue lors de la création de votre proposition. Veuillez réessayer et veillez à bien remplir les champs ci-dessous'
    end
  end

  def show
    redirect_to action: :edit
  end

  def edit
    gon.page = "edit"
    gon.proposition_tags = @proposition_tags.map{ |tag| tag._id }
    load_select_tag
  end

  def update
    params[:proposition][:tag_ids].delete("") if params[:proposition] and params[:proposition][:tag_ids].present?
    if @proposition.update_attributes params[:proposition]
      election_tag = @candidacy.election.election_tags.find(params[:election_tag_id])
      redirect_to backoffice_propositions_path(namespace_categ: election_tag.tag.namespace), notice: 'Votre proposition a été mis à jour'
    else
      load_proposition_tags
      gon.proposition_tags = @proposition_tags.map{ |tag| tag._id }
      redirect_to :back, alert: 'Une erreur est survenue lors de la mise à jour de votre proposition. Veuillez réessayer et veillez à bien remplir les champs ci-dessous'
    end
  end

  def destroy
    @proposition.destroy
    redirect_to :back, notice: 'Votre proposition a été supprimée'
  end

  protected

  def load_select_tag
    @election_tags = @candidacy.election.election_tags.where("parent_tag_id" => nil).sort_by{ |t| t.tag.name }
    
    @tags = Array.new
      i = 0
      @election_tags.each do |t|
        @tags[i] = t.children_election_tags.map &:tag
        @stock = i if t.id.to_s == params[:election_tag_id]
        i += 1
      end
  end

  def load_proposition
    @proposition ||= Proposition.where(:_id => params[:id]).first
  end

  def load_proposition_tags
    @proposition_tags ||= @proposition.tag_ids.map { |tag_id| Tag.where(:_id => tag_id).first}
  end

end

app/helpers/backoffice_helper.rb
module BackofficeHelper
  def active_menu menu
    'active' if menu == controller_name
  end

  def link_to_remove_fields(name, f, options = {})
    f.hidden_field(:_destroy) +
    link_to_function(name, "remove_fields(this)", options)
  end

  def link_to_add_fields(name, f, association, css_class)
    new_object = f.object.class.reflect_on_association(association).klass.new
    fields = f.fields_for(association, new_object, :child_index => "new_#{association}") do |builder|
      render((association).to_s.singularize + "_fields", :f => builder)
    end.html_safe
    link_to_function(name, "add_fields(this, '#{association}', '#{escape_javascript(fields)}')",  :class => css_class)
  end

  def link_to_test_link(name, website, options = {})
    if website.size != 0
      link_to_function(name, "test_link(this, '#{website}')", options)
    else
      link_to_function(name, "test_link(this)", options)
    end
  end
end

app/helpers/mobile/propositions_helper.rb
module Mobile::PropositionsHelper
end

app/helpers/web/propositions_helper.rb
module Web::PropositionsHelper
end

app/helpers/webviews/propositions_helper.rb
module Webviews::PropositionsHelper
end

app/views/backoffice/propositions/_embed_fields.html.haml
.embed
	.row
		.col-md-6= f.input :title, label: "Hypertexte"
		.col-md-6= f.input :url, label: '* ' + "URL"
		.col-md-12.col-md-offset-2.col-sm-offset-2= link_to_remove_fields "Supprimer", f, class: "btn cst-btn btn-warning"
	.row
	%hr

app/views/backoffice/propositions/_form.html.haml
.alert.alert-info
  Thème
.control-group
  = label_tag :election_tag_id, "* Thème", class: 'control-label'
  .controls
    = select_tag :election_tag_id, options_for_select(@election_tags.map.with_index{|t,i| [t.tag, t.id, {'data-index' => i }]}, params[:election_tag_id]), input_html: { class: "input-xxlarge" }

.alert.alert-info
  Sous-thèmes : sélectionnez ci-dessous un ou plusieurs thèmes sous lequel vous voudriez que votre proposition apparaisse

- if !@tags.blank?
  - if params[:election_tag_id]
    = f.association :tags, as: :select, label: "Sous-thème", collection: @tags[@stock], input_html: { class: "input-xxlarge" }
  - else
    = f.association :tags, as: :select, label: "Sous-thème", collection: @tags[0], input_html: { class: "input-xxlarge" } 
- else
  %p= "Pas de sous-thème"

.alert.alert-info
  Texte de proposition : la proposition ne doit pas faire plus de 300 caractères pour qu’elle soit lisible et facilement comparable avec les autres propositions. De plus, la proposition doit uniquement présenter une idée. Enfin, le contenu des propositions doit venir uniquement des sources officielles du candidat.
= f.input :text, label: "Texte", as: :text, input_html: { class: "input-xxlarge", rows: 10, maxlength: 300 }, hint: tag(:span, id: 'text-counter'), placeholder: '300 ' + t('backoffice.characters_max')

.alert.alert-info
  Enrichissez votre proposition : vous pouvez lier votre proposition à un contenu contextuel en utilisant des hyperlinks (par exemple : définitions, mots clés, vidéos)

= f.simple_fields_for :embeds do |embed|
  = render "embed_fields", f: embed
.embed
= link_to_add_fields "Ajouter un lien", f, :embeds, "btn cst-btn btn-primary"
%br

.form-actions
  = f.submit "Soumettre", class: "btn btn-success"
  = link_to "Retour", :back, class: 'btn'

:coffee
  $ ->
    $('#proposition_text').simplyCountable({
      counter: '#text-counter'
      maxCount: 300
      countDirection: 'up'
    })

:javascript
  var tags_j = #{@tags.to_json};
  
  $('#election_tag_id').change(function(){
    var selected = $('#election_tag_id option:selected').data("index");
    $('#proposition_tag_ids').empty();
    $('.select2-search-choice').remove();
    for (var i = 0; i< tags_j[selected].length; i++){
      $('#proposition_tag_ids').append('<option value="' + tags_j[selected][i]._id+ '">' + tags_j[selected][i].name + '</option>');
    }
  });

app/views/backoffice/propositions/edit.html.haml
%h3= @candidacy.election.name + " - " + t('backoffice.edit_proposition')
%hr

= simple_form_for @proposition, url: backoffice_proposition_path(@proposition.id), html: { class: 'form-horizontal' } do |f|
  = render "form", f: f

app/views/backoffice/propositions/index.html.haml
- if @active_tag.present?
  %h2= "Élection : " + @election_name + " - Mes propositions"
  %hr
  .hero-unit-bo
    %h4 Choisir un thème
  %ul{:class => "nav nav-pills" }
    - @lst_tags.sort_by{ |categ_tag| categ_tag.tag.name }.each do |categ_tag|
      - if(@active_tag)
        - if(categ_tag.tag.name==@active_tag.tag.name)
          %li{:class => "active" }
            - unless categ_tag.tag.icon_prefix.blank?
              = image_tag "#{categ_tag.tag.icon_prefix}32.png", style: 'width: auto; height: 24px;', onerror: "this.style.display = 'none';"
            = link_to categ_tag.tag.name, backoffice_propositions_categorie_path(categ_tag.tag.namespace), style: 'display: inline;'
        - else
          %li
            - unless categ_tag.tag.icon_prefix.blank?   
              = image_tag "#{categ_tag.tag.icon_prefix}32.png", style: 'width: auto; height: 24px;', onerror: "this.style.display = 'none';"
            = link_to categ_tag.tag.name, backoffice_propositions_categorie_path(categ_tag.tag.namespace), style: 'display: inline;'
      - else
        %li
          - unless categ_tag.tag.icon_prefix.blank?   
            = image_tag "#{categ_tag.tag.icon_prefix}32.png", style: 'width: auto; height: 24px;', onerror: "this.style.display = 'none';"
          = link_to categ_tag.tag.name, backoffice_propositions_categorie_path(categ_tag.tag.namespace), style: 'display: inline;'


  %hr
  .row
    - if @active_tag
      .col-md-4.col-sm-6
        %a{ :href => new_backoffice_proposition_path(election_tag_id: @active_tag.id.to_s), :target => '_blank' }
          .btn.btn-block
            %i.icon-plus-sign
            Nouvelle proposition
    - if @propositions_categ.any?
      .quick-search-div.col-md-6.col-md-offset-2.col-sm-6
        = form_for :search, html: {class: 'form-search', style: 'float: right;'} do |f|
          %label{:for => "quick_search"}
            = t('backoffice.search')
          .input-prepend
            %span.add-on
              %i.icon-search
            = f.text_field :search, id: "quick_search", class: "input-medium"

  - if @propositions_categ.count > 0
    .row
      .col-md-12
        %br
        %table.table.table-hover
          %thead
            %tr{style: 'border-bottom: 3px solid #B6B6B6;'}
              %th{style: 'border-right: 1px solid #dddddd; width: 10%;'}
                %b
                  = t('backoffice.sub_tag')
              %th{style: 'border-right: 1px solid #dddddd; width: 75%;'}
                = t('backoffice.proposition_text')
              %th 
                %b
                  Action
          %tbody#root-propositions
            - @propositions_categ.sort_by{ |p| p.tags.first.name }.reverse.each do |proposition|
              %tr
                %td{style: 'border-right: 1px solid #dddddd; width: 10%;'}
                  - if proposition.tags.count > 0
                    - proposition.tags.each do |tag|
                      - unless @active_tag.tag === tag
                        %b
                          = tag.name
                        %br
                  - else
                    X
                %td{style: 'border-right: 1px solid #dddddd; width: 75%;'}
                  = proposition[:text]
                  %div{style: 'margin-top: 10px; margin-bottom: 10px;'}
                    - if proposition.embeds.count > 0
                      - if proposition.embeds.count > 0
                        %b
                          Les liens de la proposition :
                          %br
                        - proposition.embeds.each do |embed|
                          %b
                            - if embed.title.present?
                              = link_to " - " + embed.title, embed.url, target: '_blank'
                            - else
                              = link_to " - " + embed.url, embed.url, target: '_blank'
                            - if embed.provider_name == "YouTube"
                              (Lien Youtube)
                            %br
                %td
                  = link_to edit_backoffice_proposition_path(proposition, election_tag_id: @active_tag.id.to_s), class: 'btn crud-btn', target: '_blank' do
                    %i.icon-pencil
                    = t('backoffice.edit')
                  = link_to backoffice_proposition_path(proposition), method: :delete, confirm: t('backoffice.alert_confirmation'), class: 'btn btn-danger crud-btn' do
                    %i.icon-remove
                    = t('backoffice.delete')
  - else 
    .row
      .col-md-12
        %br
        %br
        %h3{style: 'text-align: center;'}
          = "Aucune proposition pour ce thème"

- else 
  %h2= t('backoffice.election_target') + " : " + @election_name + " - Mes propositions"
  %hr
  %br
  .hero-unit-bo
    %h4 Choisir un thème
  .row{style: 'margin-top: 20px;'}
    .col-md-12
      - @lst_tags.sort_by{ |categ_tag| categ_tag.tag.name }.each do |categ_tag|
        = link_to backoffice_propositions_categorie_path(categ_tag.tag.namespace), class: 'theme-choose' do
          .col-md-12{style: 'text-align: left; padding-bottom: 30px; padding-top: 30px; padding-left 15px;'}
            - unless categ_tag.tag.icon_prefix.blank?
              = image_tag "#{categ_tag.tag.icon_prefix}32.png", style: 'width: auto; height: 32px;', onerror: "this.style.display = 'none';"
            = categ_tag.tag.name

app/views/backoffice/propositions/new.html.haml
%h3= @candidacy.election.name + " - " + t('backoffice.add_new_proposition')
%hr

= simple_form_for @proposition, url: backoffice_propositions_path, html: { class: 'form-horizontal' } do |f|
  - if params[:election_tag_id]
    = render "form", f: f, election_tag: true
  - else
    = render "form", f: f, election_tag: false