config/routes.rb
Joinplato::Application.routes.draw do

  # redirect www to .
  match "/" => redirect("http://voxe.org"), :constraints => {:subdomain => "www"}
  match "/*path" => redirect {|params, request| "http://voxe.org/#{params[:path]}" }, :constraints => {:subdomain => "www"}

  # 2008
  match "/election-municipales" => redirect('/')
  match "/election-municipales/" => redirect('/')
  match "/election-municipales/*path" => redirect('/')

  # sitemap
  match 'sitemap.xml' => 'web/sitemap#index', format: 'xml'

  # admin
  namespace :admin do
    match '/' => 'dashboard#index'
  end

  # New admin (Let the old live until candidate BO isn't finished)
  namespace :new_admin do
    match '/' => 'elections#index'
    resources :countries
    resources :tags
    resources :elections do
      resources :election_tags, only: [:index]
      resources :candidacies do
          get 'toggle', :defaults => { :format => 'json' }
        resources :propositions
        match 'propositions/categorie/:namespace_categ' => 'propositions#index', :as => :propositions_categorie
      end
      get 'publish', :defaults => { :format => 'json' }
      get 'unpublish', :defaults => { :format => 'json' }
      resources :tags, only: [:create]
      resources :ambassadors
      resources :contributors
    end
    resources :candidacy_candidate_profiles
    resources :candidates
    resources :tags, only: [:index, :edit, :update]
    resources :users, only: [:index]
    resources :manage_propositions, only: [:index]
  end

  # API
  namespace :api, format: :json do
    namespace :v1 do

      resources :elections, except: :index do
        member do
          post :addtag
          delete :removetag
          post :addcandidacy
          post :movetags
          post :addcontributor
          get :contributors
          post :addambassador
          get :ambassadors
          post :addcontributor
          get :contributors
        end
        collection do
          get :search
        end
      end

      resources :themes do
        member do
          post :addphoto
        end
      end

      resources :candidates do
        member do
          post :addphoto
        end
        collection do
          get :search
        end
      end

      resources :tags do
        collection do
          get :search
        end
      end

      resources :propositions do
        scope module: :user_actions do
          resource :favorite, only: [:create, :destroy]
          resource :support, only: [:create, :destroy]
          resource :against, only: [:create, :destroy]
        end
        collection do
          get :search
        end
        member do
          get :comments
          post :addcomment
          post :addembed
          delete :removeembed
          delete :removecomment
        end
      end

      resources :candidacies do
        member do
          post :addorganization
        end
      end

      resources :users do
        collection do
          get :search
          get :verify
          get :self
          put :self
          get :facebookconnect
          get :admins
        end
        member do
          put :addadmin
          put :removeadmin
        end
      end

      resources :organizations

      resources :comparisons do
        collection do
          get :search
        end
      end

      resources :countries do
        collection do
          get :search
        end
      end

      resources :cities do
        get :search, on: :collection
      end

    end
  end

  # webviews
  namespace :webviews, format: "touch" do
    resources :comparisons, only: :index
    resources :propositions, only: :show
  end

  # web-app
  namespace :embed do
    resources :elections, only: :show
    resources :live, only: :index
    resources :partners, only: :index do
      collection do
        get :huffingtonpost
      end
    end
  end

  # api doc

  match 'platform' => 'platform#index'

  namespace :platform do
    resources :endpoints do
      collection do
        get :elections
        get :candidates
        get :propositions
        get :tags
        get :candidacies
        get :users
        get :organizations
        get :countries
      end
    end
    resources :models do
      collection do
        get :election
        get :candidate
        get :proposition
        get :tag
        get :candidacy
        get :user
        get :organization
        get :country
      end
    end
    resources :embed, :only => :index do
      collection do
        get :button
        get :bookmarklet
      end
    end
    resources :mobile, :only => :index
    resources :open_data, :only => :index
  end

  devise_for :users, controllers: {
    sessions: "devise/custom_sessions"
  }

  # Back-office for candidates
  namespace :backoffice do
    root to: 'my_profiles#show'
    resources :candidacies
    resource :my_profile do
      member do
        get :thank_you
      end
    end
    resources :propositions
    match 'propositions/categorie/:namespace_categ' => 'propositions#index', :as => :propositions_categorie
  end

  # all platforms
  match 'about/' => 'Web::Static#about', :as => :about
  match 'about/how' => 'Web::Static#how', :as => :how
  match 'about/team' => 'Web::Static#team', :as => :team
  match 'about/press' => 'Web::Static#press', :as => :press
  match 'about/thanks' => 'Web::Static#thanks', :as => :thanks
  match 'apps' => 'Web::Static#apps', :as => :apps

  # touch
  scope :module => "touch", format: "touch", constraints: TouchConstraint.new do
    root to: 'application#welcome'
    get '/welcome' => 'application#welcome', :as => :welcome
    match ':namespace/:candidacies/:tag' => 'comparisons#show', :as => :compare
    match ':namespace/:candidacies' => 'tags#index', :as => :tags
    match ':namespace' => 'elections#show', :as => :election

    root to: 'elections#index'
  end

  # mobile
  scope :module => "mobile", format: "mobile", constraints: MobileConstraint.new do
    match ':namespace/:candidacies/:tag' => 'elections#compare', :as => :compare

    match 'propositions/:id' => 'propositions#show', :as => :proposition

    match ':namespace/candidacies' => 'candidacies#create', :as => :candidacies
    match ':namespace/:candidacies' => 'tags#index', :as => :tags
    match ':namespace' => 'elections#show', :as => :election

    root to: 'elections#index'
  end

  # web
  scope :module => "web", format: "html" do
    match 'welcome' => 'application#welcome', :as => :welcome

    match 'propositions/:id' => 'propositions#show', :as => :proposition
    match 'country-:countrynamespace' => 'countries#show', :as => :country
    match 'election/:electionnamespace/candidate/:candidatenamespace' => 'candidacy_candidate_profiles#show', as: :candidate_profile
    match 'citizen/:id' => 'citizen_profiles#show', as: :citizen_profiles
    match ':namespace/:candidacies/:tag' => 'comparisons#show', :as => :compare
    match ':namespace/:candidacies' => 'tags#index', :as => :tags
    match ':namespace' => 'elections#show', :as => :election

    root to: 'application#index'
  end

end

app/controllers/api/v1/elections_controller.rb
class Api::V1::ElectionsController < Api::V1::ApplicationController

  #caches_action :show, :expires_in => 1.hour
  caches_action :search, expires_in: 300.seconds, if: Proc.new { params[:published].blank? && params[:name].blank? && params[:flatten].blank? }, layout: false
  caches_action :show, expires_in: 3600.seconds, if: Proc.new { params[:published].blank? }, layout: false

  # GET /api/v1/elections/1
  def show
    @all_tags = true # since we use caching #(params[:tags] == 'all')
    @only_published_candidacies = not(params[:published] == 'all')
  end

  # GET /api/v1/elections/search
  def search
    @only_published_candidacies = false
    unless params[:published] == 'all'
      @elections = @elections.where(published: true)
      @only_published_candidacies = true
    end
    if params[:flatten] == 'true'
      # Nothing todo for the moment
    else
      @elections = @elections.where(parent_election_id: params[:parent], name: /#{params[:name]}/i).includes(:candidacies).desc(:_id).limit(50)
    end
  end

  # POST /api/v1/elections
  def create
    @election.contributors << current_user

    if @election.save
      render 'api/v1/elections/show', status: :created
    else
      render text: {errors: @election.errors}.to_json, status: :unprocessable_entity, layout: 'api_v1'
    end
  end

  # PUT /api/v1/elections/1
  def update
    if @election.update_attributes params[:election]
      #expire_action action: "show", id: @election.id

      render 'api/v1/elections/show', status: :ok
    else
      render text: {errors: @election.errors}.to_json, status: :unprocessable_entity, layout: 'api_v1'
    end
  end

  # POST /api/v1/elections/1/addtag
  def addtag
    tag = Tag.find params[:tagId]
    if params[:parentTagId]
      parent_tag = Tag.find params[:parentTagId]
    end

    @election_tag = ElectionTag.new election: @election, tag: tag, parent_tag: parent_tag

    if @election_tag.save
      #expire_action action: "show", id: @election.id
      render 'api/v1/elections/show', status: :created
    else
      render text: {errors: @election_tag.errors}.to_json, status: :unprocessable_entity, layout: 'api_v1'
    end
  end

  # POST /api/v1/elections/1/addcandidacy
  def addcandidacy
    candidates = params[:candidateIds].split(',').collect {|id| Candidate.find(id) }
    @election.candidacies.build candidates: candidates

    if @election.save
      #expire_action action: "show", id: @election.id
      render 'api/v1/elections/show', status: :created
    else
      render text: {errors: @election.errors}.to_json, status: :unprocessable_entity, layout: 'api_v1'
    end
  end

  # DELETE /api/v1/elections/1/removetag
  def removetag
    @election.election_tags.where(tag_id: params[:tagId]).destroy_all
    #expire_action action: "show", id: @election.id
    head :ok
  end

  # POST /api/v1/elections/1/movetags
  def movetags
    params[:tagIds].each_with_index do |tag_id, index|
      tag = Tag.find tag_id
      et = ElectionTag.where(election_id: @election.id, tag_id: tag.id).first
      et.update_attribute :position, index+1
    end
    render 'api/v1/elections/show', status: :ok
  end

  # POST /api/v1/elections/1/addcontributor
  def addcontributor
    @user = User.find(params[:userId])
    @election.contributors << @user
    @election.save
    if @election.save
      render 'api/v1/users/show'
    else
      render text: {errors: @user.errors}.to_json, status: :unprocessable_entity, layout: 'api_v1'
    end
  end

  # GET /api/v1/elections/1/contributors
  def contributors
    @users = @election.contributors
  end

  # POST /api/v1/elections/1/addambassador
  def addambassador
    @user = User.find(params[:userId])
    @election.ambassadors << @user
    if @election.save
      render 'api/v1/users/show'
    else
      render text: {errors: @user.errors}.to_json, status: :unprocessable_entity, layout: 'api_v1'
    end
  end

  # GET /api/v1/elections/1/contributors
  def ambassadors
    @users = @election.ambassadors
  end

end

app/controllers/embed/elections_controller.rb
class Embed::ElectionsController < ApplicationController

  layout false

  # will be reset every deploy
  #caches_action :show

  def show
    begin
      @election = Election.find params[:id]
    rescue Mongoid::Errors::DocumentNotFound
      return render text: "invalid electionId"
    end
  end

end

app/controllers/embed/live_controller.rb
class Embed::LiveController < ApplicationController
  
  layout false
  
  def index
  end
  
end

app/controllers/embed/partners_controller.rb
class Embed::PartnersController < ApplicationController
  
  def huffingtonpost
    render layout: false
  end
  
end

app/controllers/mobile/elections_controller.rb
class Mobile::ElectionsController < Mobile::ApplicationController
  
  before_filter :set_election, except: :index
  
  def index
    @elections = Election.where published: true
  end
  
  def show
    @page_title = "#{@election.name}"
  end
  
  def compare
    # candidacies
    begin
      @candidacies = @election.candidacies.select do |candidacy|
        params[:candidacies].split(',').include? candidacy.namespace
      end
    rescue
      return render text: "invalid candidacies"
    end
    
    # tag
    begin
      @tag = Tag.where({namespace: params[:tag]}).first
    rescue
      return render text: "invalid tag"
    end
    
    # title
    @page_title = @candidacies.collect { |candidacy| candidacy.name }.join(', ')
    @page_title += " - #{@tag.name}"
    @page_title += " | #{@election.name}"
    
    # election tag
    @election_tag = ElectionTag.where({election_id: @election.id, tag_id: @tag.id}).first
    return render text: "empty" unless @election_tag
        
    propositions = Proposition.where :candidacy_id.in => @candidacies.collect(&:id),
                                     :tag_ids => @tag.id
                                     
    @tags_propositions = {}
    propositions.each do |proposition|
      proposition.tags.each do |tag|
        @tags_propositions[tag.id.to_s] = [] unless @tags_propositions[tag.id.to_s]
        @tags_propositions[tag.id.to_s] << proposition
      end
    end
  end
  
end

app/controllers/new_admin/elections_controller.rb
# encoding: UTF-8
class NewAdmin::ElectionsController < AdminController
  load_and_authorize_resource find_by: :namespace

  def index
    @future_elections = load_elections(false)
    @past_elections = load_elections(true)
  end

  def edit
  end

  def new
  end

  def create
    @election.contributors << current_user
    if @election.save
      flash[:notice] = "#{@election} has been created"
      if from_election = Election.where(id: params[:election][:election_tags]).first
        @election.copy_tags_from_election(from_election)
      end
    end
    respond_with :new_admin, @election, location: new_admin_elections_path
  end

  def tags
    @election_tags = @election.election_tags.
      select{|et| et.root? }.
      sort{|et1,et2| et1.tag.name <=> et2.tag.name}
  end

  def update
    @election.update_attributes(params[:election])
    respond_with :new_admin, @election, location: new_admin_elections_path
  end

  def destroy
    if @election.destroy
      flash[:notice] = @election.to_s + " has been removed"
    else
      flash[:error] = "An error occured while deleting" + @election.to_s
    end
    respond_with :new_admin, @election, location: new_admin_elections_path
  end

  def publish
    toggle_publication("publish", true)
  end

  def unpublish
    toggle_publication("unpublish", false)
  end

  private

  def toggle_publication(action_name, state)
    @election = Election.find(params["election_id"])
    @election.published = state
    if @election.save
      flash[:notice] = @election.to_s + " has been " + action_name + "ed."
    else
      flash[:error] = "An error occured while " + action_name + "ing " + @election.to_s
    end
    #respond_with @election, location: new_admin_elections_path
  end

  def load_elections(is_past)
    @elections.asc(:date).select{ |e| 
      if !e.date.blank? 
        if is_past
          (e.date < Date.today) 
        else
          (e.date > Date.today) 
        end
      else 
        false 
      end
      }
  end
end

app/controllers/platform/embed_controller.rb
class Platform::EmbedController < ApplicationController
  
  layout 'platform'
  
  def index
    @election = Election.where(namespace: "france-presidentielle-2012").first
  end
  
  def button
  end
  
  def bookmarklet
    @election = Election.first
  end
  
end

app/controllers/touch/elections_controller.rb
class Touch::ElectionsController < Touch::ApplicationController
  
  before_filter :set_election, except: :index
  
  def index
    @options = {}
  end
  
  def show
    @options = {electionId: @election.id}
    render "index"
    # respond_to do |format|
    #   format.touch do
    #     @json = render_to_string('/api/v1/elections/show.json', layout: false)
    #   end
    # end
  end
  
end

app/controllers/web/elections_controller.rb
class Web::ElectionsController < Web::ApplicationController
  
  before_filter :set_election
  # will be reset every deploy
  caches_action :show
  
  def show
    respond_to do |format|
      format.html do
        @only_published_candidacies = true
        @all_tags = true
        @options = render_to_string('/api/v1/elections/show.json', layout: false)
        render "web/application/index"
      end
    end
  end
  
end

app/controllers/webviews/elections_controller.rb
class Webviews::ElectionsController < Webviews::ApplicationController
end

app/helpers/elections_helper.rb
module ElectionsHelper
end

app/helpers/embed/elections_helper.rb
module Embed::ElectionsHelper
end

app/helpers/embed/live_helper.rb
module Embed::LiveHelper
end

app/helpers/embed/partners_helper.rb
module Embed::PartnersHelper
end

app/helpers/mobile/elections_helper.rb
module Mobile::ElectionsHelper
end

app/helpers/touch/elections_helper.rb
module Touch::ElectionsHelper
end

app/helpers/web/elections_helper.rb
module Web::ElectionsHelper
end

app/helpers/webviews/elections_helper.rb
module Webviews::ElectionsHelper
end

app/views/embed/elections/_templates.mustache.haml
%script#application-template{type: 'text/html'}
  #header
    .twitter= link_to image_tag('share/twitter16.png'), twitter_intent_url, target: "_blank"
    .facebook= image_tag 'share/facebook16.png'
    .container

  #content
    #candidacies-list.page
    #tags-list.page

    #propositions.page
      .indicator= image_tag 'ajax-loader.gif'
      .container

  #footer
    .container
      = link_to image_tag('icons/16.png', valign: 'middle'), root_url, target: "_blank"
      = link_to "Voxe.org", root_url, target: "_blank"
      = link_to "Ajouter ce comparateur sur votre site", platform_embed_index_url, target: "_blank", id: "instructions"

%script#candidacy-cell-template{type: 'text/html'}
  :plain
    <li candidacy-id="{{candidacy.id}}">
      {{#candidacy.candidates}}
        <div class="icon"><img src="{{photo.sizes.small.url}}" width="32px" height="32px" /></div>
        <div class="name">
          <input type="checkbox" />
          {{firstName}} {{lastName}}
        </div>
      {{/candidacy.candidates}}
    </li>

#candidacies-list-template
  %ul

%script#tags-list-template{type: 'text/html'}
  %ul
    :plain
      {{#tags}}
        <li tag-id="{{id}}">
          <div class="icon"><img src="{{icon.prefix}}64{{icon.name}}" width="32px" height="32px" /></div>
          <div class="name">{{name}}</div>
        </li>
      {{/tags}}

%script#propositions-template{type: 'text/html'}
  :plain
    {{#categories}}
      <div class="category">
        <div class="category-name">{{name}}</div>

        {{#candidacies}}
          <div class="candidacy">
            {{#candidates}}
              <div class="photo">
                <img src="{{photo.sizes.small.url}}" width="44px" height="44px" />
              </div>
            {{/candidates}}

            {{#propositions}}
              <div class="proposition">
                <ul class="embeds">
                  {{#embeds}}
                    <li><a class="{{type}}" href="{{url}}" target="_blank">{{title}}</a></li>
                  {{/embeds}}
                </ul>
                {{text}}
              </div>
            {{/propositions}}
          </div>
        {{/candidacies}}

        {{#sections}}
          <div class="section">
            <div class="section-name">{{name}}</div>
            {{#candidacies}}
              <div class="candidacy">
                {{#candidates}}
                  <div class="photo">
                    <img src="{{photo.sizes.small.url}}" width="44px" height="44px" />
                  </div>
                {{/candidates}}

                {{#propositions}}
                  <div class="proposition">
                    <ul class="embeds">
                      {{#embeds}}
                        <li><a class="{{type}}" href="{{url}}" target="_blank">{{title}}</a></li>
                      {{/embeds}}
                    </ul>
                    {{text}}
                  </div>
                {{/propositions}}
                {{^propositions}}
                  <div class="proposition">
                    <a href="https://docs.google.com/spreadsheet/viewform?formkey=dGNsLWFoYXZ0LXRaRVVrdU9Tay04ZFE6MQ" target="_blank">Vous avez identifié une proposition manquante d'un candidat ? Envoyez-la nous !</a>
                  </div>
                {{/propositions}}
              </div>
            {{/candidacies}}
          </div>
        {{/sections}}
      </div>
    {{/categories}}

app/views/embed/elections/show.html.haml
!!!
%html
  %head
    %title= "#{@election.name} | Voxe"
    = stylesheet_link_tag "embed/elections"
    = javascript_include_tag "embed/elections"
    = render "layouts/partials/google_analytics"
    = render "layouts/partials/chartbeat_header"
  %body
    = render 'layouts/partials/facebook.html'
    :javascript
      $(function() {
        new VoxeElection({
          electionId: '#{@election.id}',
          tagIds: #{params['tagIds'].try(:split, ',').to_json},
          candidacyIds: #{params['candidacyIds'].try(:split, ',').to_json},
          defaultCandidacyIds: #{params['defaultCandidacyIds'].try(:split, ',').to_json},
          defaultTagId: #{params['defaultTagId'].to_json}
        });
      });
      
    #touch{style: "display: none"}
      .container
        = link_to image_tag('icons/16.png', valign: 'middle'), root_url, target: "_blank"
        = link_to "Voxe.org", root_url, target: "_blank"
      .market= link_to_app_store image_tag("embed/elections/apple-app-store.png")
      .market= link_to_android_market image_tag("embed/elections/google-app-store.png")
      
    #app
      
    #templates
      = render 'templates.mustache'

    = render "layouts/partials/chartbeat_body"
    = render 'layouts/partials/twitter.html'