config/routes.rb
Joinplato::Application.routes.draw do

  # redirect www to .
  match "/" => redirect("http://voxe.org"), :constraints => {:subdomain => "www"}
  match "/*path" => redirect {|params, request| "http://voxe.org/#{params[:path]}" }, :constraints => {:subdomain => "www"}

  # 2008
  match "/election-municipales" => redirect('/')
  match "/election-municipales/" => redirect('/')
  match "/election-municipales/*path" => redirect('/')

  # sitemap
  match 'sitemap.xml' => 'web/sitemap#index', format: 'xml'

  # admin
  namespace :admin do
    match '/' => 'dashboard#index'
  end

  # New admin (Let the old live until candidate BO isn't finished)
  namespace :new_admin do
    match '/' => 'elections#index'
    resources :countries
    resources :tags
    resources :elections do
      resources :election_tags, only: [:index]
      resources :candidacies do
          get 'toggle', :defaults => { :format => 'json' }
        resources :propositions
        match 'propositions/categorie/:namespace_categ' => 'propositions#index', :as => :propositions_categorie
      end
      get 'publish', :defaults => { :format => 'json' }
      get 'unpublish', :defaults => { :format => 'json' }
      resources :tags, only: [:create]
      resources :ambassadors
      resources :contributors
    end
    resources :candidacy_candidate_profiles
    resources :candidates
    resources :tags, only: [:index, :edit, :update]
    resources :users, only: [:index]
    resources :manage_propositions, only: [:index]
  end

  # API
  namespace :api, format: :json do
    namespace :v1 do

      resources :elections, except: :index do
        member do
          post :addtag
          delete :removetag
          post :addcandidacy
          post :movetags
          post :addcontributor
          get :contributors
          post :addambassador
          get :ambassadors
          post :addcontributor
          get :contributors
        end
        collection do
          get :search
        end
      end

      resources :themes do
        member do
          post :addphoto
        end
      end

      resources :candidates do
        member do
          post :addphoto
        end
        collection do
          get :search
        end
      end

      resources :tags do
        collection do
          get :search
        end
      end

      resources :propositions do
        scope module: :user_actions do
          resource :favorite, only: [:create, :destroy]
          resource :support, only: [:create, :destroy]
          resource :against, only: [:create, :destroy]
        end
        collection do
          get :search
        end
        member do
          get :comments
          post :addcomment
          post :addembed
          delete :removeembed
          delete :removecomment
        end
      end

      resources :candidacies do
        member do
          post :addorganization
        end
      end

      resources :users do
        collection do
          get :search
          get :verify
          get :self
          put :self
          get :facebookconnect
          get :admins
        end
        member do
          put :addadmin
          put :removeadmin
        end
      end

      resources :organizations

      resources :comparisons do
        collection do
          get :search
        end
      end

      resources :countries do
        collection do
          get :search
        end
      end

      resources :cities do
        get :search, on: :collection
      end

    end
  end

  # webviews
  namespace :webviews, format: "touch" do
    resources :comparisons, only: :index
    resources :propositions, only: :show
  end

  # web-app
  namespace :embed do
    resources :elections, only: :show
    resources :live, only: :index
    resources :partners, only: :index do
      collection do
        get :huffingtonpost
      end
    end
  end

  # api doc

  match 'platform' => 'platform#index'

  namespace :platform do
    resources :endpoints do
      collection do
        get :elections
        get :candidates
        get :propositions
        get :tags
        get :candidacies
        get :users
        get :organizations
        get :countries
      end
    end
    resources :models do
      collection do
        get :election
        get :candidate
        get :proposition
        get :tag
        get :candidacy
        get :user
        get :organization
        get :country
      end
    end
    resources :embed, :only => :index do
      collection do
        get :button
        get :bookmarklet
      end
    end
    resources :mobile, :only => :index
    resources :open_data, :only => :index
  end

  devise_for :users, controllers: {
    sessions: "devise/custom_sessions"
  }

  # Back-office for candidates
  namespace :backoffice do
    root to: 'my_profiles#show'
    resources :candidacies
    resource :my_profile do
      member do
        get :thank_you
      end
    end
    resources :propositions
    match 'propositions/categorie/:namespace_categ' => 'propositions#index', :as => :propositions_categorie
  end

  # all platforms
  match 'about/' => 'Web::Static#about', :as => :about
  match 'about/how' => 'Web::Static#how', :as => :how
  match 'about/team' => 'Web::Static#team', :as => :team
  match 'about/press' => 'Web::Static#press', :as => :press
  match 'about/thanks' => 'Web::Static#thanks', :as => :thanks
  match 'apps' => 'Web::Static#apps', :as => :apps

  # touch
  scope :module => "touch", format: "touch", constraints: TouchConstraint.new do
    root to: 'application#welcome'
    get '/welcome' => 'application#welcome', :as => :welcome
    match ':namespace/:candidacies/:tag' => 'comparisons#show', :as => :compare
    match ':namespace/:candidacies' => 'tags#index', :as => :tags
    match ':namespace' => 'elections#show', :as => :election

    root to: 'elections#index'
  end

  # mobile
  scope :module => "mobile", format: "mobile", constraints: MobileConstraint.new do
    match ':namespace/:candidacies/:tag' => 'elections#compare', :as => :compare

    match 'propositions/:id' => 'propositions#show', :as => :proposition

    match ':namespace/candidacies' => 'candidacies#create', :as => :candidacies
    match ':namespace/:candidacies' => 'tags#index', :as => :tags
    match ':namespace' => 'elections#show', :as => :election

    root to: 'elections#index'
  end

  # web
  scope :module => "web", format: "html" do
    match 'welcome' => 'application#welcome', :as => :welcome

    match 'propositions/:id' => 'propositions#show', :as => :proposition
    match 'country-:countrynamespace' => 'countries#show', :as => :country
    match 'election/:electionnamespace/candidate/:candidatenamespace' => 'candidacy_candidate_profiles#show', as: :candidate_profile
    match 'citizen/:id' => 'citizen_profiles#show', as: :citizen_profiles
    match ':namespace/:candidacies/:tag' => 'comparisons#show', :as => :compare
    match ':namespace/:candidacies' => 'tags#index', :as => :tags
    match ':namespace' => 'elections#show', :as => :election

    root to: 'application#index'
  end

end

app/controllers/api/v1/comparisons_controller.rb
class Api::V1::ComparisonsController < Api::V1::ApplicationController
  
  skip_load_and_authorize_resource
      
  caches_action :search, expires_in: 3600.seconds, if: Proc.new { params[:afterTimestamp].blank? }, layout: false
  
  def search
    # returns the last 20 comparisons
    @events = Event.where(name: "comparison").desc(:created_at).limit(20)
    unless params[:afterTimestamp].blank?
      @events = @events.where :created_at.gt => Time.at(params[:afterTimestamp].to_i)
    end
  end
  
end

app/controllers/touch/comparisons_controller.rb
class Touch::ComparisonsController< Touch::ApplicationController
  
  before_filter :set_election
 
  def show
    @options = {electionId: @election.id}
    render "touch/elections/index"
  end
  
end

app/controllers/web/comparisons_controller.rb
class Web::ComparisonsController < Web::ApplicationController
  before_filter :load_countries
  before_filter :load_elections
  before_filter :load_election
  before_filter :load_candidacies, if: ->{ params[:candidacies] }
  before_filter :load_tag, if: ->{ params[:tag] }
  before_filter :load_propositions, if: ->{ @candidacies and @tag }

  def compare
    @countries_with_upcoming_elections = @elections
  end

  protected
  def load_countries
    elections = Election.where(:country_id.ne => nil, :date.ne => nil)
    @countries = { with_upcoming_elections: Set.new, with_past_elections: Set.new }
    @countries = elections.reduce(@countries) do |countries, election|
      if election.upcoming?
        countries[:with_upcoming_elections] << election.country
      else
        countries[:with_past_elections] << election.country
      end
      countries
    end
  end

  def load_elections
    unless @country = Country.where(namespace: params[:country_namespace]).first
      @country = @election.country if load_election
    end
    if @country.present?
      @elections = @country.elections
    else
      @elections = []
    end
  end

  def load_election
    @election ||= Election.where(namespace: params[:namespace]).first
  end

  def load_candidacies
    @candidates = Candidate.where(:namespace.in => params[:candidacies].split(','))
    @candidacies = Candidacy.where(election_id: @election, :candidate_ids.in => @candidates.map(&:id))
  end

  def load_tag
    @tag = Tag.where(namespace: params[:tag]).first
  end

  def load_propositions
    @propositions = Proposition.where(:candidacy_id.in => @candidacies.map(&:id), tag_ids: @tag.id)

    # group propostions
    @groupedPropositions = ElectionTag.where(election_id: @election.id, tag_id: @tag.id).first.children_election_tags.reduce({}) do |memo, election_tag|
      memo[election_tag.tag] = election_tag.children_election_tags.reduce({}) do |memo2, et2|
        memo2[et2.tag] = @candidacies.reduce({}) do |memo3, candidacy|
          memo3[candidacy] = @propositions.select do |p|
            p.tags.include?(et2.tag) && p.candidacy == candidacy
          end
          memo3
        end
        memo2
      end
      memo
    end
  end
end

app/controllers/webviews/comparisons_controller.rb
class Webviews::ComparisonsController < Webviews::ApplicationController

  before_filter :log, only: :index
  caches_action :index, expires_in: 3600.seconds, cache_path: Proc.new { webviews_comparisons_path(params) }

  def index
    # election
    if params[:electionId].blank?
      return render text: "params electionId can't be blank"
    end
    begin
      @election = Election.find params[:electionId]
    rescue Mongoid::Errors::DocumentNotFound
      return render text: "invalid electionId"
    end

    # candidates
    if params[:candidacyIds].blank?
      return render text: "params candidacyIds can't be blank"
    end
    begin
      @candidacies = Candidacy.find params[:candidacyIds].split(',')
    rescue Mongoid::Errors::DocumentNotFound
      return render text: "invalid candidacyIds"
    end

    # tag
    if params[:tagId].blank?
      return render text: "params tagId can't be blank"
    end
    begin
      @tag = Tag.find params[:tagId]
    rescue Mongoid::Errors::DocumentNotFound
      return render text: "invalid tagId"
    end

    # election tag
    @election_tag = ElectionTag.where({election_id: @election.id, tag_id: @tag.id}).first
    return render text: "empty" unless @election_tag

    conditions = {}
    conditions[:tag_ids.in] = params[:tagId].split(',') unless params[:tagId].blank?
    conditions[:candidacy_id.in] = params[:candidacyIds].split(',') unless params[:candidacyIds].blank?

    propositions = Proposition.where(conditions)

    @tags_propositions = {}
    propositions.each do |proposition|
      proposition.tag_ids.each do |tag_id|
        @tags_propositions[tag_id.to_s] = [] unless @tags_propositions[tag_id.to_s]
        @tags_propositions[tag_id.to_s] << proposition
      end
    end
  end

  private
  def log
    begin
      Event.create name: 'comparison', candidacy_ids: params[:candidacyIds].split(','), tag_ids: [params[:tagId].to_s], ip_address: request.remote_ip.to_s, user_driven: params[:userDriven]
    rescue
    end
  end

end

app/helpers/api/v1/comparisons_helper.rb
module Api::V1::ComparisonsHelper
end

app/helpers/touch/comparisons_helper.rb
module Touch::ComparisonsHelper
end

app/helpers/web/comparisons_helper.rb
module Web::ComparisonsHelper
end

app/helpers/webviews/comparisons_helper.rb
module Webviews::ComparisonsHelper
end

app/views/web/comparisons/_propositions_list.html.haml
= image_tag candidacy.photo_url(:small), height: '60px', width: '60px'
- propositions.each do |proposition|
  .proposition
    .text= proposition.text

app/views/web/comparisons/compare.html.haml
#pages-container
  #pages
    #countries.page
      .page-container
        #countries-list-container
          .help
            %span 1. Choose a country
          #countries-list
            .category Upcoming elections
            #countries-upcoming-list
              - @countries[:with_upcoming_elections].each do |country|
                .country
                  = link_to country_path(country) do
                    = image_tag "https://voxe.s3.amazonaws.com/countries/#{country.namespace}.jpg"
                    .name= country.name
              .country
                %a(href="https://docs.google.com/spreadsheet/viewform?fromEmail=true&formkey=dFRwZWdTMTFZQTc5UHhBeHZKTkwxaFE6MQ")
                  %img(src="https://voxe.s3.amazonaws.com/countries/add.jpg")
                  .name Add your country
            .clear
            .category Previous elections
            #countries-previous-list
              - @countries[:with_past_elections].each do |country|
                .country
                  = link_to country_path(country) do
                    = image_tag "https://voxe.s3.amazonaws.com/countries/#{country.namespace}.jpg"
                    .name= country.name
            .clear
    #elections.page
      .page-container
        #elections-list-container
          .help
            %span 2. Choose an election
          #elections-list
            - @elections.each do |election|
              = link_to compare_path(election) do
                .election
                  .name= election.name
                  .facepile
                    - election.candidacies.each do |candidacy|
                      = image_tag candidacy.photo_url(:small), height: '30px', width: '30px'
    #candidacies.page
      .page-container
        #candidacies-list-container
          .help
            %span 3. ... then choose two candidates, and...
          #candidacies-list
            - if @election
              - @election.candidacies.published.each do |candidacy|
                .candidacy{data: {candidacy: {namespace: candidacy.namespace}}}
                  .image
                    = image_tag candidacy.photo_url(:small), height: '50px', width: '50px'
                  .name= candidacy.name
              :coffeescript
                $ ->
                  new CandidaciesSelectorView
                    el: $('#candidacies-list')
                    electionNamespace: #{@election.namespace.to_json}
                    selectedCandidacies: #{(@candidacies || []).map(&:namespace).to_json}
    #tags.page
      .page-container
        .help
          %span 4. ... choose a theme
        %ul#tags-list
          - if @election
            - @election.root_election_tags.map(&:tag).each do |tag|
              = link_to compare_path(@election, (@candidacies || []).map(&:namespace).join(','), tag.namespace) do
                %li
                  .icon
                    = image_tag "#{tag.icon_prefix}32.png"
                  .name= tag.name
    #comparison-page.page
      #comparison-container
        #comparison
          - if @propositions.present? && @propositions.any?
            .tag-image
              = image_tag "#{@tag.icon_prefix}64.png", height: '64px', width: '64px'
            .tag
              %span= @tag.name
            - @groupedPropositions.each do |tag1, sub_tags|
              .tag
                %span= tag1.name
              - sub_tags.each do |tag2, candidacies|
                .tag
                  %span= tag2.name
                .candidacies
                  .candidacy.left
                    - candidacy = candidacies.keys.first
                    - propositions = candidacies.values.first
                    = render 'propositions_list', propositions: propositions, candidacy: candidacy
                  .candidacy.right
                    - candidacy = candidacies.keys.last
                    - propositions = candidacies.values.last
                    = render 'propositions_list', propositions: propositions, candidacy: candidacy
                  .clear